### ISSUE TITLE
es5 file is an es6 file

### ISSUE THREAD

**Issue by notoriousb1t** [davidkpiano/nm8#2]
I'm attempting to include this in https://github.com/notoriousb1t/polymorph using npm and it looks like the es5 file is an es6 file.

**Comment by davidkpiano** [comment]
Uh oh, seems like we need to change some config settings. Are you able to do that?

**Comment by notoriousb1t** [comment]
Yep.  I'll see if I can figure it out and put in a PR

**Comment by notoriousb1t** [comment]
Cool 😄   Let me know if you can republish to npm. I could just copy and paste it 😉, but it feels better to take it as an upstream dependency instead.
